services:
  - type: web
    name: medi-ai-dashboard
    env: static
    buildCommand: mkdir -p build && cp index.html build/
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

